version: '3'

services:
  certbot:
    image: lparet/docker-ubuntu-certbot
    container_name: certbot
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"